### ISSUE TITLE
[BUG] /wt list not showing Pokemon that are in there

### ISSUE THREAD

**Issue by NebulaEvie** [ObliqueNetwork/Terra#1820]
**Describe the bug**
I looked over the /wt list, to see if Yveltal Cen put in Titans WT pool was still in there after people in chat said it was gone. I confirmed it was gone. 10 minutes later I got it from WT.

**To Reproduce**
1. Go to /wt list
2. check pokemon in list
3. check it some time later
4. obtain a pokemon that supposedly was not there

**Expected behavior**
I expected not to be able to get the Yveltal. as it was no longer on the list

**Screenshots**
N/A

**Username:**
Evie666

**Server name (all applicable):**
Titan (could be all)

**Logs:**
N/A

**Additional context**
N/A

**Comment by StrideMate** [comment]
Thanks for the report! Wonder trade has had a few updates since this report, I believe the issue has been fixed however it is hard for me to replicate this issue myself. I did try it once and received a Pokemon that was in the current wonder trade pool and list, If you happen to see this happen again please do reopen this ticket or create another one! thanks and closing!
