### ISSUE TITLE
[Kits] Juices of different NBT data

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1877]
Juices received from /kits and juices made via infuser have different NBT data and cannot stack.
Furthermore a sign shop selling kit juices doesn't recognize legitimately made EV Juices as stock and vice versa

1. Infuse 2 berries into a juice
2. redeem a `/kit` that contains respective juice
3. Attempt to combine juices of various methods in inventory

All juices regardless of origin to behave with each other in both inventories and shops alike.

![juice1](https://user-images.githubusercontent.com/17133410/191829910-8c535564-9c04-4169-b596-7d92ca6682c9.png)
![juice2](https://user-images.githubusercontent.com/17133410/191829928-52c5616d-9dab-40a3-82df-970667b666f1.png)

Orion, Likely all.

**Comment by KittyKatzyn** [comment]
o/ DeathNight!

Can confirm this is a Pixelmon bug, so I shall pass 'er along their way!

Thanks!
Katzyn

**Comment by KittyKatzyn** [comment]
Just as an update - I recieved a reply from the Pixelmon devs, which essentially said this is intentional because EV juices made with different ingredients will had different values in regards to how much happiness/stats they provide, so unfortunately they cannot make them stack, or they lose those different values.
