### ISSUE TITLE
Alcremie Unobtainable?

### ISSUE THREAD

**Issue by RyanDHackett** [ObliqueNetwork/Terra#1907]
**Describe the bug**
Treats don't seem to be held by milcery at the moment. Perhaps the treats were meant to be added to spawn shop when they were removed from held items?

**To Reproduce**
Catch 3 pc boxes of Milcery. See no held items.

**Expected behavior**
A held treat every 20 catches.

**Username:**
Cindermaji

**Server name (all applicable):**
Orion

**Additional context**
Other pokemon are being caught with held items regularly. Shellder with Pearls, Morelull with tiny mushrooms, etc. It just seems to be Milcery. Perhaps RNG really isn't on my side? After over 100 catches it's gotten to feel like it's bugged/removed unintentionally.

**Comment by KittyKatzyn** [comment]
Hi there! Thanks for your report!

Yes, Alrcemie is bugged in the main mod - [see here](https://pixelmonmod.com/tracker.php?p=2&t=19033)

It should be fixed in 9.0.11 according to current predictions :)

As this is a Pixelmon bug and has already been reported to their trackers, I will close this, but you can keep an eye on the above link for updates!  Thank you!

**Comment by RyanDHackett** [comment]
Awesome thanks! Good to know!
