### ISSUE TITLE
[CTD] EXP candy spam results in CTD

### ISSUE THREAD

**Issue by Deathnight7976** [ObliqueNetwork/Terra#1952]
Level snorlax past 47 minecraft angy

1. Get snorlax lvl 47
2. Lvl snorlax > 47
3. Crash

No crash. Crash bad.

Deathnight7976

Orion, Likely all, maybe just a me issue dunno?

Crash report:
[SnorlaxCrash.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9851204/SnorlaxCrash.txt)

**Comment by KittyKatzyn** [comment]
Have looked into this with Death and we can't get reproduce it atm; can reopen if we figure our the method :)

**Comment by Deathnight7976** [comment]
This bug instead of occuring on a specific mon when leveling up seems to occur when spamming different exp candies, I was scrolling between XS and S exp candies as there on different CD's and upon my Dottlers level up I crashed to desktop.

CrashReport:
[EXPCAndy Crash.txt](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/9954321/EXPCAndy.Crash.txt)

Vod:
https://www.youtube.com/watch?v=2iTEoQclvWQ

**Comment by KittyKatzyn** [comment]
Turns out this was a Pixelmon + Optifine issue!  If you use your scroll wheel immediately when the leveling screen pops up, you crash!

Thanks for all the testing and patience, Death! Issue has been forwarded to the Pixelmon public and internal trackers! https://pixelmonmod.com/tracker.php?p=2&t=19508
