### ISSUE TITLE
[Palette Mods/Alphas] Making a mon an Alter skin, makes it an Alpha skin.

### ISSUE THREAD

**Issue by skateboardkid97** [ObliqueNetwork/Terra#1967]
**Describe the bug**
When you use a palette mod on say, a Larvesta, like Killua_Tempest did, his mon aka starter was read as an alpha mon. For reference's sake and so it can be reviewed by an admin+, I have kept the Larvesta until I'm good to give it back because I want it to be reviewable by someone. :]
![image](https://user-images.githubusercontent.com/42111124/200183582-0a62be7c-f5fc-471d-8758-ac7e29905a31.png)
You can see his Larvesta glows now obviously, and it is definitely an Alpha mon.
![image](https://user-images.githubusercontent.com/42111124/200183853-216a6ce1-9b5e-498d-8f39-150df8619951.png)
(I tried making the 'Alpha Form' look as best as it could, but no matter which texture pack I use, the text always goes behind. :[ )

**To Reproduce**
1. Take a Palette Mod
2. Edit your mon to an Alter palette
3. If it has an Alpha form also, it will become an Alpha.

**Expected behavior**
Alpha mons not being 'fakeable' I guess?

**Username:**
BUGJUUICER/BUG-JUICER#0940
Killua_Tempest/(He does not have a discord.)

**Server name (all applicable):**
Orion, likely all.

**Comment by StrideMate** [comment]
Hi, So I've just tested this and it seems to still be a issue, I don't know if alter and alpha Pokemon have the same textures but they definitely looked the same. However with testing though, I did find that the form showing seems to be fixed as it was alter it was labelled "Alter Palette" So that seems to be on the fixed side, I will leave this open until I hear further information on if it's supposed to look like that or not!

![2023-01-26_21 17 39](https://user-images.githubusercontent.com/78794976/214811822-f8efdbbf-09d7-4c09-8256-70e4fa2c8140.png)
![2023-01-26_21 17 46](https://user-images.githubusercontent.com/78794976/214811836-04d60785-9369-4e0b-90c1-dcbdeadbea6e.png)

**Comment by Deathnight7976** [comment]
This no longer occurs via palette mod, however it is possible to achieve via form mod which is an intended feature.
