### ISSUE TITLE
Pokeball wont craft

### ISSUE THREAD

**Issue by killercreechan** [ObliqueNetwork/Terra#2007]
**Describe the bug**
after hunting an electrode and getting pokeball parts from it i had tried to make a pokeball from it and it wouldnt let me could be items from before the update bugging out.

**To Reproduce**
1. kill electrode
2. try to craft ball with both parts it gives

**Expected behavior**
to be looked into and the problem solved 

**Username:**
Killercreechan

**Server name (all applicable):**
titan possibly all servers

**Comment by Rasgnarok** [comment]
What pokeball type was this, and what were the IDs when you received the parts?

**Comment by killercreechan** [comment]
i noticed it was the parts from electrodes in tesla and lids created pre update ill log on later and get more info for you

**Comment by KittyKatzyn** [comment]
Sorry for the late response!

This is, at the core, a Pixelmon issue, which HAS been fixed for the soon-to-be-released 9.1.1; however, since we have custom drops in our pokemon-drops file, we'll need to amend our drops file after we've got that version on our servers.  So, for now, I'll leave this ticket open, but will put this on the to do list for after the next version releases!  Thanks!

**Comment by KittyKatzyn** [comment]
This issue has been fixed! Changes should take place when the servers restart :)

Ty!
