### ISSUE TITLE
Nebula Store issues

### ISSUE THREAD

**Issue by Chunkkss** [ObliqueNetwork/Terra#2041]
Keys:

Limited Edition crate keys on the shop are still showing as the Thanksgiving rewards.

Ranks: 
/breed and /hatch don't show the new commands /breeding and /breakegg

/skin command doesn't run due to bungee network service (error that i received)
 *Remove this probs*

/ride doesn't work on players nor your own pokemon ( hasn't ever worked tho)
*Remove this probs*

/se doesn't work on editing signs (also hasn't ever worked)
*Not sure if this will be fixed or removed*

/redeem gui is now /redeemcosmetics (i believe) and /redeemcosmetics doesn't work either (I think this worked at one point, but haven't been able to get it to ever work since reset happened)

**Comment by StrideMate** [comment]
Most I can say for /se is that it works but as to how it works is different, I've been able to edit signs by shifting and right clicking on a sign, I believe this is sign edit because normal people without ranks haven't been able to do it at least to my knowledge could always double check with seeing if a non-rank player can do it or not!

**Comment by Chunkkss** [comment]
> Just tested, and this is the case. Will just have to be changed in the store description so players know this as well

**Comment by StrideMate** [comment]
Yeee, I figured this out the very first time I bought omen, I was randomly spamming buttons and when I clicked shift+right-click I could edit it, I then tested with another non-ranked player and they couldn't do it :p
