### ISSUE TITLE
[Battle Tower] Getting kicked after completing a floor

### ISSUE THREAD

**Issue by TheKeyblade** [ObliqueNetwork/Terra#2190]
**Describe the bug**
When you finish a floor of the battle tower you sometimes get kicked from a random floor 

**To Reproduce**
1. Go to /battletower
2. Complete a floor
3. Get kicked from battle tower

**Expected behavior**
Being able to continue the tower with no issues. Only being kicked upon blacking out.

**Server name (all applicable):**All

**Comment by CenizaRey** [comment]
We need client logs of when this occurs otherwise we have no idea how it happens, when, or why

**Comment by iJaySin** [comment]
Not OP but I think this is my client log. I find myself very often (like 70% of the time) getting teleported out to spawn after I beat the ground floor. A theory I have would be that the arena map is causing the issue because one of the arenas shows the opponent's mons falling into the void during battle but I haven't checked/compared it out much.
[techniclauncher_2023-06-09.log](https://github.com/NebulaMC-GG/Bugs-and-Issues/files/11708352/techniclauncher_2023-06-09.log)

**Comment by WisconsinWinters** [comment]
fixed numerous issues with incorrect teams in battletower, closing.
