### ISSUE TITLE
[Legendary Spawns] Lowered Spawns since Update

### ISSUE THREAD

**Issue by Xalouz** [ObliqueNetwork/Terra#2194]
**Describe the Bug**
Since the pixelmon 9.1.4 update the legendary spawns have been taking a lot longer than before, especially during what is for most players the night. Before the update a legend would spawn every 1-3 hours, with 3 hours being long. Since the update it has been taking up to 12 hours, even when the spawns were doubled for a while it didnt really change it back to how it was before the update. Did something change in how leg spawns are calculated, or did something not go over to the new update? 

**Expected behavior**
Find out if something is different in the legendary pokemon spawns, change it back to how it used to be or in a similar way so people that are not online for entire days have a chance at catching a legendary.

**Username:**
Xalou

**Server name (all applicable):**
Orion (Probably also Titan & Atlas)

**Comment by SeekerOfChaos** [comment]
Well I said the same thing but mine wasn't acknowledge... but I agree with this statement. I'd think with the amount of money I've put in they'd atleast recognize my claim but nah.

**Comment by CenizaRey** [comment]
The gap between legendary spawns is measured by ticks in the config files of the server. There has been no change in this number since Nebula was first released in June 2022.

We have acknowledged the claim that legendary spawns are broken countless times. This is not the first github ticket to be made on the topic, and it won’t be the last. Sometimes when there’s a drought, people jump the gun and claim the entire system is completely broken when in reality it’s just a bit of bad luck.

I can personally assure you nothing has changed with legendary spawns

**Comment by Xalouz** [comment]
> 

Awesome. Someone told me no-one had made a ticket about it yet, which is why I made one. I think it is because the longer waiting times started with the update, and we might have had a placebo effect/confirmation bias because of this. Thank you for making the time for it though :)

**Comment by Rasgnarok** [comment]
Closing ticket, pre-reset issue.
