### ISSUE TITLE
[Plushies] Always become 'Small' size when placed

### ISSUE THREAD

**Issue by FarDiamond** [ObliqueNetwork/Terra#2310]
**Describe the bug**
When you get a random plushie; they're given in random sizes (sizes listed in the description of the item) if you place down 2 plushies that are the same species but different sizes they're the same size. When picked up, they both are seen as size 'Small' in the description.  This happens when any plushie of varying sizes are placed regardless of species and original listed size

**To Reproduce**
1. Get random plushie with size not small
2. Place plushie
3. Pick up plushie
4. Plushie now 'Small' size

**Expected behavior**
Plushies should retain the sizes they were assigned when given to the player

**Screenshots**
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134177870/494902a7-955d-4521-9474-d52f340bbba9)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134177870/16542f3e-5824-4ffd-b1a3-cc520f48c259)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134177870/601b5a83-e81c-4c1b-abbb-f666ed0465b4)
![image](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134177870/ac5cbabf-b1eb-4741-aba5-e17f968f6b52)

**Username:**
FarDiamond3049 (nicknamed Far)

**Server name (all applicable):**
Titan

**Logs:**
_Where needed, please find your logs with the method down below. Make sure to include the file, or better yet, use a site like https://pastebin.com/ to add it to the ticket without copy pasting all the contents of the file._
For the Minecraft Launcher : _C:\Users\USER\AppData\Roaming\.minecraft\logs_
For the Technic Launcher: _C:\Users\USER\AppData\Roaming\.technic\modpacks\pixelmon-reforged\logs_
For the ATLauncher: _C:\Users\USER\AppData\Roaming\ATLauncher\Instances\PixelmonCraft\logs_
For the Twitch Launcher: _C:\Users\USER\Documents\Curse\Minecraft\Instances\PACK\logs_

**Additional context**
srmod peyton has observed this oddity

**Comment by WisconsinWinters** [comment]
Forwarded to internal tracker

**Comment by Rasgnarok** [comment]
Needs re-testing to see if issue persists

**Comment by Oryso** [comment]
Still changes sizes if you place and then pick up again, but seems its changing to Ordinary instead of Small.

![2024-02-29_00 09 37](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/73126486-0d1f-4085-b861-faed77f98dec)
![2024-02-29_00 09 44](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/4c01ed38-4be7-4400-8a0f-94befd615931)

![2024-02-29_00 11 07](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/0d157ede-d3a6-4233-912a-9a27d17dfdd8)
![2024-02-29_00 11 13](https://github.com/NebulaMC-GG/Bugs-and-Issues/assets/134505379/c6424030-a8ee-4b97-8caf-c4f5adcf7904)

**Comment by WisconsinWinters** [comment]
forwarded to internal tracker
